openapi: 3.0.0
info:
  title: ToDoList
  version: 0.0.1

components:
  securitySchemes:
    bearerAuth:
     type: http
     scheme: bearer
     bearerFormat: JWT

  schemas:
    Pagination:
      type: object
      properties:
        offset:
          type: integer
          minimum: 0
          example: 0
        limit:
          type: integer
          example: 100

    Deadline:
      enum:
        - TODAY
        - WEEK
        - SOMEDAY

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date
          example: "2023‑09‑25 17:45:30.005"
        message:
          type: string
          format: date
          example: 'Not Found'

    TaskRequest:
      type: object
      properties:
        description:
          type: string
          example: 'Call Maria'
        deadline:
          '$ref': '#/components/schemas/Deadline'
        user_id:
          type: integer
          format: int64
          example: 115

    TaskResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 12345
        user_id:
          type: integer
          format: int64
          example: 12345
        description:
          type: string
          example: 'Call Maria'
        deadline:
          type: string
          example: 'today'

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100
        name:
          type: string
          example: 'Alex'
        email:
          format: email
          example: 'abc@mail.com'

    UserRequest:
      type: object
      properties:
        name:
          type: string
          example: 'Alex'
        email:
          type: string
          format: email
          example: 'abc@mail.com'
        password:
          type: string
          example: '1234'

    AuthRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: 'abc@mail.com'
        password:
          type: string
          example: '1234'

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdHJhc2hub0Bn'

paths:
  /tasks:
    post:
      summary: 'Crate task'
      description: 'Registers a new task'
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/TaskRequest'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/TaskResponse'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ErrorResponse'

    get:
      summary: 'All tasks'
      description: 'Returns the list of all registered tasks'
      tags:
        - Tasks
      parameters:
        - name: pagination
          in: query
          schema:
            '$ref': '#/components/schemas/Pagination'
          required: true
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  '$ref': '#/components/schemas/TaskResponse'

  /tasks/{id}:
    get:
      summary: 'Task info'
      description: 'Returns info about a particular task'
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/TaskResponse'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ErrorResponse'
              example:
                timestamp: '2023‑09‑25 17:45:30.005'
                message: 'Not found'

    patch:
      summary: 'Edit task'
      description: 'Edit info of an existing task'
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/TaskRequest'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/TaskResponse'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ErrorResponse'
              example:
                timestamp: '2023‑09‑25 17:45:30.005'
                message: 'Bad Request'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ErrorResponse'
              example:
                timestamp: '2023‑09‑25 17:45:30.005'
                message: 'Not found'

    delete:
      summary: 'Delete task'
      description: 'Deletes a particular task'
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: 'OK'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ErrorResponse'
              example:
                timestamp: '2023‑09‑25 17:45:30.005'
                message: 'Not found'

  /tasks/deadline/{deadline}:
    get:
      summary: 'All tasks'
      description: 'Returns the list of all registered tasks'
      tags:
        - Tasks
      parameters:
        - name: deadline
          in: path
          schema:
            '$ref': '#/components/schemas/Deadline'
          required: true
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  '$ref': '#/components/schemas/TaskResponse'

  /users/new:
    post:
      summary: 'Crate a user'
      description: 'Registers a new user'
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/UserRequest'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/UserResponse'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ErrorResponse'

  /auth/authenticate:
    post:
      summary: 'Get auth token'
      description: 'Returns auth token based on e-mail and password'
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/AuthResponse'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ErrorResponse'